### ISSUE TITLE
Help getting started with python-gcm

### ISSUE THREAD

**Issue by spark85** [geeknam/python-gcm#100]
Hi, 

I'm just trying to get a sample up and running and I don't understand how to use script in the instructions.  Is that the python-gcm program?  How do I run the script from the command line?  This looks like an awesome app, but it could use a bit more on getting started. 

Thanks, 
David

**Comment by mnemonicflow** [comment]
Hello,

This project is used a Python module, you have to include it in your Python code/script to be able to use it.

As explained in the README.rst file you can create a send_push_notifications.py script with the following:
```
from gcm import GCM

gcm = GCM(API_KEY)
data = {'param1': 'value1', 'param2': 'value2'}

# JSON request
reg_ids = ['12', '34', '69']
response = gcm.json_request(registration_ids=reg_ids, data=data)
```

You get the API_KEY from: https://developers.google.com/mobile/add
You can get notification tokens from the Android app that you wrote after you register with GCM services on the Android device or the server if you sent the tokens to your server.
Further details: https://developers.google.com/cloud-messaging/

I will try to update the README and provide example scripts on how to use python-gcm, thanks for the suggestion!
