### ISSUE TITLE
No support for setting up priority for a given message?

### ISSUE THREAD

**Issue by ishansharma29** [geeknam/python-gcm#102]
Hi,

I can see that original GCM service also sets up priority for a given message e.g. https://developers.google.com/cloud-messaging/concept-options?hl=en#setting-the-priority-of-a-message

But python gcm doesn't give us that capability. Can this be incorporated ?

Also, I can see issues that are not being answered, is this still maintained? 

Thanks,
Ishan

**Comment by mnemonicflow** [comment]
@ishansharma29 

You can specify the priority parameter to the json_request object in the 2nd parameter.

Something like:
```
response = gcm.json_request(registration_ids=registration_ids, data=notification,
                                collapse_key='app_update',
                                priority='high',
                                restricted_package_name="com.awesomecompany.awesomeapp",
                                delay_while_idle=False)
```

The project is still maintained.

**Comment by ishansharma29** [comment]
Hi,

Thanks for a detailed explanation on both of my issues. I tried using
collapse_key='app_update'
for more than two notification and kept my internet off. When I turned my
internet on, I still got more than 1 notification (I guess messages with
the same collapse key should get collapsed and I should be getting just a
single notification) or do I have to make some changes at the client side
as well?

**Comment by mnemonicflow** [comment]
According to [Liftime of a message](https://developers.google.com/cloud-messaging/concept-options#lifetime)
the collapsing *should* be done on Google's GCM servers if the device is offline or delay_while_idle=True

```
[...] [If the device is offline], [the notification] will be stored in the GCM connection servers until the device is awake. And that's where the collapse_key flag plays a role: if there is already a message with the same collapse key (and registration token) stored and waiting for delivery, the old message will be discarded and the new message will take its place (that is, the old message will be collapsed by the new one). However, if the collapse key is not set, both the new and old messages are stored for future delivery.
```

Can you please set debug=True on the GCM object and check the output printed by ```GCM.log('Request data: {0}', data)``` to see if the two HTTP POST requests have the same collapse_key?

**Comment by mnemonicflow** [comment]
@ishansharma29 If you were using the plaintext_request method please try the code in the [develop branch](https://github.com/geeknam/python-gcm/tree/develop)
