### ISSUE TITLE
request fail

### ISSUE THREAD

**Issue by 631068264** [geeknam/python-gcm#112]
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='gcm-http.googleapis.com', port=443): Max retries exceeded with url: /gcm/send (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10273a050>: Failed to establish a new connection: [Errno 65] No route to host',))

how to solve it.

**Comment by josven** [comment]
I can replicate this error when I try to send_topic_message in a request/response cycle (django).
But this goes away when I invoke send_topic_message directly from python shell.

**Comment by mnemonicflow** [comment]
@631068264 The 'no route to host' problem is outside the bounds of the gcm.py program. Check your network configuration on the machine your running the script. 

You can use the host, nslookup, dig, ping, tracepath commands to help with the troubleshooting:
- http://www.tecmint.com/linux-network-configuration-and-troubleshooting-commands/
- http://www.cyberciti.biz/tips/no-route-to-host-error-and-solution.html
