### ISSUE TITLE
Update to support Notification messages in the FCM payload

### ISSUE THREAD

**Issue by viju85** [geeknam/python-gcm#117]
Currently there is support for data messages in the payload from the server. I also would like to send notification messages along with the payload from the server to the client.

Is there an existing way, if not, we need to add it.

https://firebase.google.com/docs/cloud-messaging/concept-options

**Comment by mnemonicflow** [comment]
You can send both notification and data.

See https://github.com/geeknam/python-gcm/issues/99#issuecomment-168643895 and https://github.com/geeknam/python-gcm/issues/113#issuecomment-239937396

**Comment by viju85** [comment]
Thanks! May be this is not the right place to post this, but i noticed that when i send FCM payload when app is in background, i see the notification message being shown which is as per docs, but i see native notifications for every notification message received. When my app was in the background, i received 3 push messages and i now see 3 native notifications in the notification tray. Why are they not getting collapsed ? By default, according to FCM docs, all notification messages are collapsible.
