### ISSUE TITLE
Best practice for utf-8 messages?

### ISSUE THREAD

**Issue by steveobd** [geeknam/python-gcm#14]
Hi Nam - 

what is the best practice for using utf-8 encoded messages?       Should we always do data.encode("utf-8") before passing the data?

Otherwise, the urlencoder chokes

**Comment by pcompassion** [comment]
inside `construct_payload`

        if is_json:
            payload = json.dumps(payload)

could be

    payload = json.dumps(payload).encode('utf-8')
