### ISSUE TITLE
Sending non-blocking requests to GCM

### ISSUE THREAD

**Issue by pramttl** [geeknam/python-gcm#39]
I noticed that I had to wait for the `json_request` call to return before I could be able to send my next messge to GCM.  In other words, the following call is a blocking call.

```
    res = gcm.json_request(registration_ids=reg_ids, data=data,)
```

It would be nice to have an `async_json_request` function that sends the message to GCM and returns immediately so that we can send our next message.

I think there might be need to to use CCS (XMPP) for this instead of HTTP based GCM, but I am not completely aware of the implementation details.

**Comment by sirvon** [comment]
@pramttl what is Message Queuing API's? what service is that google's or rackspace?

**Comment by baris-erdem** [comment]
I wrote [this](https://github.com/baris-erdem/asyncgcm). Take a look at it.
