### ISSUE TITLE
Example Documentation Error

### ISSUE THREAD

**Issue by jblayney** [geeknam/python-gcm#49]
The check:

if error is 'NotRegistered' 

Can cause problems. If 'NotRegistered' comes back as unicode, this check will fail. Many times JSON comes back as exclusively unicode depending on libraries that are used. The correct syntax that will work in both cases (unicode and non-unicode) is:

if error == 'NotRegistered'

Thanks!

**Comment by mnemonicflow** [comment]
Fixed! https://github.com/geeknam/python-gcm/blob/master/gcm/gcm.py#L223
