### ISSUE TITLE
using requests library instead of urllib

### ISSUE THREAD

**Issue by auvipy** [geeknam/python-gcm#53]

**Comment by srirams6** [comment]
+1

**Comment by geeknam** [comment]
I think this is finally a good idea. Most of users have been requesting Python3 compatible version and there are some PRs that try to replace urllib2 with urllib. Using `requests` would definitely help in this scenario.

+1

**Comment by geeknam** [comment]
https://github.com/geeknam/python-gcm/pull/60

**Comment by geeknam** [comment]
Fixed with https://github.com/geeknam/python-gcm/pull/60
