### ISSUE TITLE
GCMUnavailableException handling on json_request

### ISSUE THREAD

**Issue by ytkang** [geeknam/python-gcm#58]
def json_request(self, registration_ids, data=None, collapse_key=None,
                         delay_while_idle=False, time_to_live=None, retries=5, dry_run=False):
            ...
                response = self.make_request(payload, is_json=True)
       
this will raise GCMUnavailableException and it couldn't be failover.
please put try/exception phrase like this,

            try:
                response = self.make_request(payload, is_json=True)
            except GCMUnavailableException:
                unsent_reg_ids = registration_ids

**Comment by gabriel-laet** [comment]
Hey @ytkang, I've opened a pull-request that tries to address this issue:
https://github.com/geeknam/python-gcm/pull/63

**Comment by ytkang** [comment]
@gabriel-laet Great! Thanks.
