### ISSUE TITLE
AttributeError: 'bool' object has no attribute 'encode'

### ISSUE THREAD

**Issue by user0007** [geeknam/python-gcm#61]
data = {'param1': 'value1', 'param2': True}
    reg_id = '12'
    gcm.plaintext_request(registration_id=reg_id, data=data)

**Comment by mnemonicflow** [comment]
What Python version are you using? 
Can you provide a traceback?

**Comment by mnemonicflow** [comment]
This problem is due to the urlencode_utf8 method https://github.com/geeknam/python-gcm/pull/80/files#diff-464232c9a5921970b623c217c57caae7L83 , whis is going to be removed and the problem will be fixed!
