### ISSUE TITLE
URL

### ISSUE THREAD

**Issue by razor-1** [geeknam/python-gcm#62]
According to google docs, the HTTP URL should be 'https://gcm-http.googleapis.com/gcm/send'

**Comment by mnemonicflow** [comment]
Indeed, according to https://developers.google.com/cloud-messaging/http the Google Cloud Messaging (GCM) HTTP connection server should be **https://gcm-http.googleapis.com/gcm/send**. I'll make a pull request regarding this issue.

**Comment by geeknam** [comment]
Thanks Alex
