### ISSUE TITLE
plaintext_request fails

### ISSUE THREAD

**Issue by nostrademons** [geeknam/python-gcm#66]
plaintext_request calls make_request with is_json=False, which then runs the data through urlencode_utf8 to get a urlencoded string.  The data param of requests.post requires a dictionary (this is a difference from urllib2), so the regid and other parameters are not passed to GCM, which then errors out.

**Comment by rapzak** [comment]
Agree -
I had to comment out these 2 lines to get it to work:
        if not is_json:
            data = urlencode_utf8(data)

I do not know the issue behind... maybe different version of the url lib...

**Comment by mnemonicflow** [comment]
This problem occurs due to double percent encoding. The requests library already encodes the values passed in the `data` parameter of the post method. 
This issue will be fixed by #77 soon
