### ISSUE TITLE
MissingRegistration error not handled

### ISSUE THREAD

**Issue by nostrademons** [geeknam/python-gcm#67]
Or rather, it's partially handled.  This error may be returned by GCM if registration_id is missing.  Normally this is checked upon entry to plaintext_request/json_request, but because of #66, the registration_id isn't being encoded correctly and so GCM errors out silently.  It should at least be checked in raise_error so that a failure doesn't pass silently to the rest of the app.

**Comment by mnemonicflow** [comment]
Will be fixed by #81
