### ISSUE TITLE
No response json after request

### ISSUE THREAD

**Issue by jordan2816** [geeknam/python-gcm#72]
response = gcm.json_request(registration_ids=reg_ids, data=data)

response always {}

**Comment by sbose78** [comment]
I face the same thing, even though I can see the gcm message in the log output.

**Comment by mnemonicflow** [comment]
And no exception was thrown? Also can you log the HTTP response after the request is made in https://github.com/geeknam/python-gcm/blob/master/gcm/gcm.py#L190 ?

**Comment by mnemonicflow** [comment]
@sbose78 From the logs it looks like the notification is being received by your device of virtue of the onMessage callback being called from inside the GCMIntentService class, so it's alright until there. If you don't see the notification afterwards it's a problem with your client code.
