### ISSUE TITLE
Topic Messaging Support

### ISSUE THREAD

**Issue by Kudo** [geeknam/python-gcm#73]
Dear Sir/Madam,

I am writing to inquire if python-gcm to support [Topic Messaging](https://developers.google.com/cloud-messaging/topic-messaging).
Currently, there are no way to custom payload outside of `data` field.
So I am not able to add the `"to": "/topics/foo-bar"`.

Do you have any plans to add such feature?
If you need help to contribute the code and create a PR, please feel free to let me know.
My thought is simple to add an `topic=None` parameter to both `json_request()` and `plaintext_request()` interfaces.

Thanks.

**Comment by geeknam** [comment]
Sure feel free to submit a pull request

On Saturday, 15 August 2015, Kudo Chien <notifications@github.com> wrote:

> Dear Sir/Madam,
>
> I am writing to inquire if python-gcm to support Topic Messaging
> <https://developers.google.com/cloud-messaging/topic-messaging>.
> Currently, there are no way to custom payload outside of data field.
> So I am not able to add the "to": "/topics/foo-bar".
>
> Do you have any plans to add such feature?
> If you need help to contribute the code and create a PR, please feel free
> to let me know.
> My thought is simple to add an topic=None parameter to both json_request()
> and plaintext_request() interfaces.
>
> Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geeknam/python-gcm/issues/73>.
>


-- 
Regards,
Nam Ngo

**Comment by Kudo** [comment]
@geeknam I've added #74, please review if that is fine for you since I did some interfaces changes.
Please feel free to give me comments if any.

Thanks.
