### ISSUE TITLE
RTFM link is broken

### ISSUE THREAD

**Issue by BenVanCitters** [geeknam/python-gcm#76]
I want to use this module but I am way to dumb to figure it out and the RTFM link (http://developer.android.com/guide/google/gcm/gcm.html) resolves to https://developers.google.com/cloud-messaging/.

What is "registration_id" and how do you obtain one?  Very few of the current GCM docs mention this item or where it can be sourced from and the example GCM app contains no mention of it.  Is it legacy/deprecated verbage?  No matter what I put in that field it doesn't work.

Is there anyone out there who know how to use this lib correctly or at least how to obtain the necessary keys/id's to get it to work with the GCM example app ( https://developers.google.com/cloud-messaging/android/start )?

**Comment by mnemonicflow** [comment]
Look at the [Reference](https://developers.google.com/cloud-messaging/http-server-ref) documentation and search for "registration_id"
