### ISSUE TITLE
Unable to generate rpm from dist-utils

### ISSUE THREAD

**Issue by melodous** [geeknam/python-gcm#88]
Hi,

Trying to generate a rpm package from dist-utils ends with error because setup.py license line don't follow the standards. 

From https://docs.python.org/2/distutils/setupscript.html#additional-meta-data:
"license, license for the package,	short string".
In this context short string is "A single line of text, not more than 200 characters.", but currently this field is filled with the content of LICENSE file which is a multiline text.

```
python setup.py bdist_rpm
......
error: line 14: Unknown tag: Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
error: query of specfile build/bdist.linux-x86_64/rpm/SPECS/python-gcm.spec failed, can't parse
error: Failed to execute: "rpm -q --qf '%{name}-%{version}-%{release}.src.rpm %{arch}/%{name}-%{version}-%{release}.%{arch}.rpm\\n' --specfile 'build/bdist.linux-x86_64/rpm/SPECS/python-gcm.spec'"
````

**Comment by mnemonicflow** [comment]
@melodous Should be fixed by https://github.com/geeknam/python-gcm/commit/cd9a5d9a2f19832dd7ff5ed69da6a6f9cf905f17
