### ISSUE TITLE
Not able to access data in service worker

### ISSUE THREAD

**Issue by ravikrn** [geeknam/python-gcm#97]
I have called gcm api using following code:

from gcm import GCM

gcm = GCM(API_KEY)
data = {'param1': 'value1', 'param2': 'value2'}
reg_id = '12'
gcm.plaintext_request(registration_id=reg_id, data=data)

But in serviceworker file I am not getting data sent via gcm api.
event.data is empty in service worker file

**Comment by mnemonicflow** [comment]
@ravikrn What is service worker? Please try again but this time enable the logging and *read* the logs.
See if in the output you find any errors listed on https://developers.google.com/cloud-messaging/http-server-ref#error-codes or something else.

You can enable the logging by setting the debug=True on the GCM object.
`gcm = GCM(API_KEY, debug=True)`

If you can't find the problem please attach log output and the exact code you are using to send the notifications.
