### ISSUE TITLE
python gcm also for IOS

### ISSUE THREAD

**Issue by ishansharma29** [geeknam/python-gcm#99]
Currently we can only use this wrapper for push notifications to Android devices. Can this also be done for IOS ? is there any difference in the procedure?

**Comment by mnemonicflow** [comment]
@ishansharma29 The mechanism is the same for sending downstream push notifications to either Android or iOS devices.
python-gcm supports sending push notification to iOS devices also.

For iOS you have to do the following things on the **iOS client** app:
* https://developers.google.com/cloud-messaging/downstream#receiving-messages-on-an-ios-client-app 
* https://developers.google.com/cloud-messaging/ios/client

The general idea is this:

Obtain a Registration Token
```
Before it can receive messages, an iOS application needs to register with both Apple Push Notification service (APNs) and the GCM connection server. 
When a client app registers with GCM, it receives a registration token, which it must then send to the app server (the APNs device token is not sent to the server). 
The client app must store a boolean value indicating whether the registration token has been sent to the server. 
```

Receive messages through the GCM APNs interface
```
Once your client app has a registration token, it can receive messages through the GCM APNs interface. 
Your application server can send messages with a notification payload through GCM's APNs interface. 
Messages with or without a notification payload can set content_available to true, which is analogous to the content-available key of the APNs aps dictionary.
```

As per [HTTP Connection Server Reference](https://developers.google.com/cloud-messaging/http-server-ref):
```
content_available 	Optional, JSON boolean 	On iOS, use this field to represent content-available in the APNS payload. When a notification or message is sent and this is set to true, an inactive client app is awoken. On Android, data messages wake the app by default. On Chrome, currently not supported.
```
Also please see the above HTTP Connection Server Reference for iOS specific details and Notification payload parameters specific to iOS

```
 notification = {
        "title": "App Update",
        "message": "Tap here to start the update.",
        "uri": "market://details?id=com.awesomecompany.awesomeapp"
    }
registration_ids = ['aaaZZZ', 'bbbZZZ']

response = gcm.json_request(registration_ids=registration_ids, data=notification,
                                collapse_key='app_update',
                                priority='high',
                                restricted_package_name='com.awesomecompany.awesomeapp',
                                delay_while_idle=False,
                                content_available=True)

```

But there are some additional steps which are specific to **iOS clients**,  i.e. Provisioning APNs SSL Certificates, etc. Please see the first two URLs.

**Comment by anthonysutardja** [comment]
This was really helpful. Might be useful to include in the README
